services:
  postgres:
    image: postgres:14-alpine
    container_name: ${POSTGRES_CONTAINER}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init-db:/docker-entrypoint-initdb.d
    networks:
      craft-network:
        ipv4_address: ${POSTGRES_IP}
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ${BACKEND_CONTAINER}
    ports:
      - "${BACKEND_PORT}:8080"
    environment:
      NODE_ENV: ${NODE_ENV}
      DATABASE_URL: ${DATABASE_URL}
      KIOSK_MODE: ${KIOSK_MODE}
      KIOSK_RESET_INTERVAL_MINUTES: ${KIOSK_RESET_INTERVAL_MINUTES}
    depends_on:
      - postgres
    networks:
      craft-network:
        ipv4_address: ${BACKEND_IP}
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        KIOSK_MODE: ${KIOSK_MODE}
    container_name: ${FRONTEND_CONTAINER}
    ports:
      - "${FRONTEND_PORT}:80"
    depends_on:
      - backend
    networks:
      craft-network:
        ipv4_address: ${FRONTEND_IP}
    restart: unless-stopped

networks:
  craft-network:
    driver: bridge
    ipam:
      config:
        - subnet: ${NETWORK_SUBNET}
          gateway: 172.28.0.1

volumes:
  postgres_data:
