<template>
  <div class="component-form">
    <h1>{{ isNewComponent ? $t('components.newComponent') : $t('components.editComponent') }}</h1>

    <div v-if="loading" class="loading">
      {{ $t('common.loading') }}
    </div>

    <div v-else-if="error" class="error">
      {{ error }}
    </div>

    <form v-else @submit.prevent="saveComponent" class="form">
      <div v-if="!isNewComponent" class="form-group">
        <label for="sku">{{ $t('components.sku') }}</label>
        <input type="text" id="sku" v-model="component.sku" disabled class="form-control form-control-disabled">
        <small class="form-text text-muted">{{ $t('components.skuAutoGenerated') }}</small>
      </div>

      <div class="form-group">
        <label for="name">{{ $t('components.name') }} *</label>
        <input 
          type="text" 
          id="name" 
          v-model="component.name" 
          required 
          class="form-control"
        >
      </div>

      <div class="form-group">
        <label for="description">{{ $t('components.description') }}</label>
        <textarea id="description" v-model="component.description" class="form-control" rows="3"></textarea>
      </div>
      
      <div class="form-group">
        <label for="quantity">{{ $t('components.quantity') }}</label>
        <input 
          type="number" 
          id="quantity" 
          v-model.number="component.quantity" 
          min="0" 
          step="1" 
          class="form-control"
          :placeholder="$t('components.quantityAvailablePlaceholder')"
        >
        <small class="form-text text-muted">{{ $t('components.quantityAvailableHelp') }}</small>
      </div>

      <h2>{{ $t('materials.title') }}</h2>
      <div v-if="loadingMaterials" class="loading">
        {{ $t('materials.loadingMaterials') }}
      </div>
      <div v-else>
        <div class="materials-list">
          <div v-for="(material, index) in component.materials" :key="index" class="material-item">
            <div class="material-header">
              <h3>{{ $t('materials.materialNumber', { number: index + 1 }) }}</h3>
              <button type="button" @click="removeMaterial(index)" class="btn btn-sm btn-danger">
                {{ $t('common.remove') }}
              </button>
            </div>

            <div class="form-group">
              <label :for="`material-${index}`">{{ $t('materials.title') }} *</label>
              <select :id="`material-${index}`" v-model="material.materialId" required class="form-control"
                @change="updateMaterialCost(index)">
                <option value="">{{ $t('common.selectMaterial') }}</option>
                <option v-for="availableMaterial in availableMaterials" :key="availableMaterial.id"
                  :value="availableMaterial.id">
                  {{ availableMaterial.name }} ({{ availableMaterial.unitOfMeasure }})
                </option>
              </select>
            </div>

            <div class="form-group">
              <label :for="`quantity-${index}`">{{ $t('common.quantity') }} *</label>
              <input type="number" :id="`quantity-${index}`" v-model.number="material.quantity" required min="0.01"
                step="0.01" class="form-control">
            </div>

            <div class="form-group">
              <label :for="`use-material-cost-${index}`">{{ $t('materials.useMaterialCost') }}</label>
              <div class="checkbox-container">
                <input type="checkbox" :id="`use-material-cost-${index}`" v-model="material.useMaterialCost">
              </div>
            </div>

            <div v-if="!material.useMaterialCost" class="form-group">
              <label :for="`custom-cost-${index}`">{{ $t('materials.customCostPerUnit') }} *</label>
              <input type="number" :id="`custom-cost-${index}`" v-model.number="material.customCost" required min="0"
                step="0.01" class="form-control">
            </div>

            <div v-if="material.materialId && material.quantity" class="cost-summary">
              <p>
                <strong>{{ $t('common.totalCost') }}:</strong>
                {{ $formatCost(calculateMaterialCost(material) || 0) }}
                ({{ $formatQuantity(material.quantity) }} ×
                {{ material.useMaterialCost
                  ? $formatCost(this.getMaterialCost(material.materialId) || 0)
                  : $formatCost(material.customCost || 0)
                }})
              </p>
            </div>
          </div>
        </div>

        <button type="button" @click="addMaterial" class="btn btn-secondary">
          {{ $t('materials.addMaterial') }}
        </button>
      </div>

      <div class="total-cost" v-if="component.materials && component.materials.length > 0">
        <h3>{{ $t('components.totalComponentCost') }}: {{ $formatCost(calculateTotalCost() || 0) }}</h3>
      </div>

      <div class="form-actions">
        <button type="submit" class="btn btn-primary" :disabled="saving">
          {{ saving ? $t('common.saving') : $t('common.save') }}
        </button>
        <button type="button" @click="cancel" class="btn btn-secondary">
          {{ $t('common.cancel') }}
        </button>
      </div>
    </form>
  </div>
</template>

<script>
import componentService from '../services/componentService';
import materialService from '../services/materialService';

export default {
  name: 'ComponentForm',
  props: {
    id: {
      type: String,
      default: null
    }
  },
  data() {
    return {
      component: {
        name: '',
        description: '',
        quantity: 0,
        materials: []
      },
      availableMaterials: [],
      materialCosts: {}, // Memorizza i costi dei materiali
      loading: false,
      loadingMaterials: false,
      saving: false,
      error: null
    };
  },
  computed: {
    isNewComponent() {
      return !this.id;
    }
  },
  created() {
    this.fetchMaterials();
    if (!this.isNewComponent) {
      this.fetchComponent();
    } else {
      // Aggiungi un materiale vuoto per iniziare
      this.addMaterial();
    }
  },
  methods: {
    async fetchComponent() {
      this.loading = true;
      this.error = null;

      try {
        const response = await componentService.getComponent(this.id);
        const componentData = response.data.component;
        const materials = response.data.materials || [];

        this.component = {
          ...componentData,
          materials: materials.map(material => ({
            materialId: material.materialId || material.material_id,
            quantity: material.quantity,
            customCost: material.customCost || material.custom_cost,
            useMaterialCost: material.useMaterialCost !== undefined ? material.useMaterialCost : material.use_material_cost
          }))
        };

        // Se non ci sono materiali, aggiungi un materiale vuoto
        if (this.component.materials.length === 0) {
          this.addMaterial();
        }
      } catch (error) {
        console.error('Error fetching component:', error);
        this.error = this.$t('errors.fetchComponent');
      } finally {
        this.loading = false;
      }
    },

    async fetchMaterials() {
      this.loadingMaterials = true;

      try {
        const response = await materialService.getAllMaterials();
        this.availableMaterials = response.data;

        // Memorizza i costi dei materiali
        this.availableMaterials.forEach(material => {
          this.materialCosts[material.id] = material.costPerUnit;
        });
      } catch (error) {
        console.error('Error fetching materials:', error);
        this.error = this.$t('errors.fetchMaterials');
      } finally {
        this.loadingMaterials = false;
      }
    },

    addMaterial() {
      this.component.materials.push({
        materialId: '',
        quantity: 1,
        useMaterialCost: true,
        customCost: 0
      });
    },

    removeMaterial(index) {
      this.component.materials.splice(index, 1);
    },

    updateMaterialCost(index) {
      const material = this.component.materials[index];
      if (material.materialId && material.useMaterialCost) {
        const materialCost = this.getMaterialCost(material.materialId);
        material.customCost = materialCost;
      }
    },

    getMaterialCost(materialId) {
      const material = this.availableMaterials.find(m => m.id === materialId);
      // Assicurati che il valore restituito sia un numero
      const cost = material ? material.costPerUnit : 0;
      return typeof cost === 'number' ? cost : parseFloat(cost) || 0;
    },

    calculateMaterialCost(material) {
      if (!material.materialId || !material.quantity) {
        return 0;
      }

      const unitCost = material.useMaterialCost
        ? this.getMaterialCost(material.materialId)
        : (material.customCost || 0);

      return unitCost * material.quantity;
    },

    calculateTotalCost() {
      return this.component.materials.reduce((total, material) => {
        return total + this.calculateMaterialCost(material);
      }, 0);
    },

    async saveComponent() {
      // Validazione
      if (!this.component.name) {
        alert(this.$t('errors.componentNameRequired'));
        return;
      }

      // Verifica che ci sia almeno un materiale
      if (this.component.materials.length === 0) {
        alert(this.$t('errors.atLeastOneMaterial'));
        return;
      }

      // Verifica che tutti i materiali abbiano un ID e una quantità
      const invalidMaterial = this.component.materials.find(
        material => !material.materialId || !material.quantity
      );

      if (invalidMaterial) {
        alert(this.$t('errors.invalidMaterial'));
        return;
      }

      // Verifica che i materiali con useMaterialCost = false abbiano un customCost
      const invalidCustomCost = this.component.materials.find(
        material => !material.useMaterialCost && (!material.customCost && material.customCost !== 0)
      );

      if (invalidCustomCost) {
        alert(this.$t('errors.customCostRequired'));
        return;
      }

      this.saving = true;

      try {
        const componentData = {
          name: this.component.name,
          description: this.component.description,
          quantity: this.component.quantity || 0,
          materials: this.component.materials
        };

        if (this.isNewComponent) {
          await componentService.createComponent(componentData);
        } else {
          await componentService.updateComponent(this.id, componentData);
        }

        this.$router.push('/components');
      } catch (error) {
        console.error('Error saving component:', error);
        alert(this.$t('errors.saveComponent'));
      } finally {
        this.saving = false;
      }
    },

    cancel() {
      this.$router.push('/components');
    }
  }
};
</script>

<style scoped>
.component-form {
  padding: 20px;
  max-width: 800px;
  margin: 0 auto;
}

h1 {
  margin-bottom: 20px;
}

h2 {
  margin-top: 30px;
  margin-bottom: 15px;
  font-size: 1.5rem;
}

.form {
  background-color: #fff;
  padding: 20px;
  border-radius: 8px;
  box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
}

.form-group {
  margin-bottom: 15px;
}

.form-group label {
  display: block;
  margin-bottom: 5px;
  font-weight: bold;
}

.form-control {
  width: 100%;
  padding: 8px;
  border: 1px solid #ddd;
  border-radius: 4px;
  font-size: 14px;
}

.checkbox-container {
  display: flex;
  align-items: center;
}

.checkbox-container input[type="checkbox"] {
  margin-right: 8px;
}

.materials-list {
  margin-bottom: 20px;
}

.material-item {
  background-color: #f8f9fa;
  padding: 15px;
  border-radius: 4px;
  margin-bottom: 15px;
}

.material-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 15px;
}

.material-header h3 {
  margin: 0;
  font-size: 1.2rem;
}

.cost-summary {
  margin-top: 10px;
  padding: 10px;
  background-color: #e9ecef;
  border-radius: 4px;
}

.total-cost {
  margin-top: 20px;
  padding: 15px;
  background-color: #e9ecef;
  border-radius: 4px;
  text-align: right;
}

.form-actions {
  margin-top: 30px;
  display: flex;
  justify-content: flex-end;
  gap: 10px;
}

.btn-primary {
  background-color: var(--secondary);
  color: var(--surface);
}

.btn-secondary {
  background-color: var(--oxford-blue-muted);
  color: var(--surface);
}

.btn-danger {
  background-color: var(--danger);
  color: var(--surface);
}

.btn:disabled {
  opacity: 0.7;
  cursor: not-allowed;
}

.loading,
.error {
  text-align: center;
  padding: 20px;
  background-color: #f8f9fa;
  border-radius: 4px;
  margin-bottom: 20px;
}

.error {
  color: #dc3545;
}
</style>